workflows:
  ios-simulator-build:
    name: iOS Simulator Build Workflow
    environment:
      xcode: latest
      cocoapods: default
      kotlin_version: 1.9.0
    scripts:
      - name: Install dependencies
        script: |
          # Install CocoaPods dependencies if you are using them
          cd iosApp && pod install
      - name: Build for iOS Simulator
        script: |
          # Build the shared framework for use in iOS
          ./gradlew :shared:packForXcode -PXCODE_CONFIGURATION=Debug -PXCODE_ARCHS=x86_64
      - name: Build the iOS App
        script: |
          # Build the iOS app for the simulator (no signing needed)
          xcodebuild \
            -workspace iosApp/iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
            clean build
    artifacts:
      - build/ios
