workflows:
  ios-simulator-build:
    name: iOS Simulator Build Workflow
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          # Install CocoaPods dependencies if you're using them
          cd iosApp && pod install
      - name: Build shared module for iOS simulator
        script: |
          # Build the shared framework for use in the iOS app (x86_64 for simulator)
          ./gradlew :shared:packForXcode -PXCODE_CONFIGURATION=Debug -PXCODE_ARCHS=x86_64
      - name: Build the iOS app for simulator
        script: |
          # Build the iOS app for the simulator without signing
          xcodebuild \
            -workspace iosApp/iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
            clean build
    artifacts:
      - build/ios
